<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
                <span class="sr-only"><?= $this->translate('header.menu.toggle'); ?></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><?= $this->translate('site.title'); ?></a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <?php if ($this->user->isLoggedIn()) { ?>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/"><?= $this->translate('header.menu.item.home'); ?> <span class="sr-only">(<?= $this->translate('header.menu.current'); ?>)</span></a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <form action="/logout" method="post" class="logout-form">
                            <input type="hidden" name="csrfToken" value="<?= base64_encode($this->csrfToken->get()); ?>">
                            <input type="submit" name="submit" value="<?= $this->translate('header.menu.item.logout.%', [$this->user->username]); ?>">
                        </form>
                    </li>
                </ul>
            <?php } ?>
        </div>
    </div>
</nav>
