<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?= $this->translate('site.title'); ?>CodeCollab Demo Application</title>
        <?= $this->minifier->css(['/css/default.min.css', '/css/custom.css'], '/css/min.css'); ?>
    </head>
    <body>
        <?= $this->render('/blocks/header.phtml'); ?>
        <?= $content; ?>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
    </body>
</html>
